/**
 * Sample Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model


case class MapSight (
  /* Unique id of a sight. */
  id: Option[String],
  /* Full name of sight. */
  name: Option[String],
  /* Link to image sights. */
  photo: Option[String],
  /* Latitude number */
  latitude: Option[Double],
  /* Longitude number */
  longitude: Option[Double]
)

